version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: my-node-app       # ganti dengan nama repo ECR kamu
    IMAGE_TAG: latest                  # bisa juga pakai $CODEBUILD_RESOLVED_SOURCE_VERSION biar unik
    AWS_REGION: ap-southeast-1         # ganti dengan region ECR kamu

phases:
  pre_build:
    commands:
      - echo "🔑 Login to Amazon ECR..."
      - aws --version
      - $(aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin <AWS_ACCOUNT_ID>.dkr.ecr.$AWS_REGION.amazonaws.com)

      - echo "📦 Installing dependencies..."
      - npm install
      - echo "🧪 Running tests..."
      - npm test
  build:
    commands:
      - echo "⚙️ Building the Docker image..."
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG <AWS_ACCOUNT_ID>.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo "🚀 Pushing the Docker image to ECR..."
      - docker push <AWS_ACCOUNT_ID>.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo "✅ Build completed successfully."
artifacts:
  files:
    - '**/*'
  discard-paths: yes
