version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: selecao
    IMAGE_TAG: latest
    AWS_REGION: ap-southeast-2
    AWS_ACCOUNT_ID: "767397791789"

phases:
  install:
    commands:
      - echo "📦 Installing dependencies..."
      - npm install

  pre_build:
    commands:
      - echo "🔑 Logging in to Amazon ECR..."
      - aws --version
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - echo "🧪 Running tests (will not fail build if tests fail)..."
      - npm test || echo "⚠️ Tests failed, continuing build..."

  build:
    commands:
      - echo "⚙️ Building the Docker image..."
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

  post_build:
    commands:
      - echo "🚀 Pushing the Docker image to ECR..."
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo "✅ Build completed successfully."
      - printf '[{"name":"%s","imageUri":"%s"}]' $IMAGE_REPO_NAME $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
