version: 0.2

phases:
  install:
    commands:
      - echo "Installing SonarScanner..."
      - curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
      - unzip -q sonar-scanner.zip -d /opt
      - export PATH=$PATH:/opt/sonar-scanner-5.0.1.3006-linux/bin
      - echo "SonarScanner installed"

  build:
    commands:
      - echo "Running SonarQube analysis..."
      - sonar-scanner \
          -Dsonar.projectKey=my-node-app \
          -Dsonar.sources=. \
          -Dsonar.host.url=$SONAR_HOST_URL \
          -Dsonar.login=$SONAR_TOKEN
